server:
  port: 9090
swagger:
  mock-api-url: http://dev-893974910.us-west-2.elb.amazonaws.com:9098
wiremock:
  port: 9098
  host: http://dev-893974910.us-west-2.elb.amazonaws.com
spring:
  application:
    name: flexbets-sport
  docker:
    compose:
      enabled: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: mock
