server:
  port: 9090
swagger:
  mock-api-url: http://${WIRE_MOCK_HOST}:9098
wiremock:
  port: 9098
  host: localhost
spring:
  application:
    name: flexbets-sport
  docker:
    compose:
      enabled: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    active: mock
