package io.limeup.flexbets.sport.mapper;

import io.limeup.flexbets.sport.model.IoPlayersStats;
import io.limeup.flexbets.sport.model.dto.IoSportsDataPlayerStatsDTO;
import org.springframework.stereotype.Component;

@Component
public class IoPlayersStatsMapper {

    public void merge(IoPlayersStats entity, IoSportsDataPlayerStatsDTO dto) {
        entity.setStatId(dto.getStatID());
        entity.setTeamId(dto.getTeamID());
        entity.setPlayerId(dto.getPlayerID());
        entity.setSeasonType(dto.getSeasonType());
        entity.setSeason(dto.getSeason());
        entity.setName(dto.getName());
        entity.setTeam(dto.getTeam());
        entity.setPosition(dto.getPosition());
        entity.setPositionCategory(dto.getPositionCategory());
        entity.setStarted(dto.getStarted());
        entity.setBattingOrder(dto.getBattingOrder());
        entity.setGlobalTeamId(dto.getGlobalTeamID());
        entity.setAverageDraftPosition(dto.getAverageDraftPosition());
        entity.setAuctionValue(dto.getAuctionValue());
        entity.setUpdated(dto.getUpdated());
        entity.setGames(dto.getGames());
        entity.setFantasyPoints(dto.getFantasyPoints());
        entity.setAtBats(dto.getAtBats());
        entity.setRuns(dto.getRuns());
        entity.setHits(dto.getHits());
        entity.setSingles(dto.getSingles());
        entity.setDoublesCount(dto.getDoubles());
        entity.setTriples(dto.getTriples());
        entity.setHomeRuns(dto.getHomeRuns());
        entity.setRunsBattedIn(dto.getRunsBattedIn());
        entity.setBattingAverage(dto.getBattingAverage());
        entity.setOuts(dto.getOuts());
        entity.setStrikeouts(dto.getStrikeouts());
        entity.setWalks(dto.getWalks());
        entity.setHitByPitch(dto.getHitByPitch());
        entity.setSacrifices(dto.getSacrifices());
        entity.setSacrificeFlies(dto.getSacrificeFlies());
        entity.setGroundIntoDoublePlay(dto.getGroundIntoDoublePlay());
        entity.setStolenBases(dto.getStolenBases());
        entity.setCaughtStealing(dto.getCaughtStealing());
        entity.setPitchesSeen(dto.getPitchesSeen());
        entity.setOnBasePercentage(dto.getOnBasePercentage());
        entity.setSluggingPercentage(dto.getSluggingPercentage());
        entity.setOnBasePlusSlugging(dto.getOnBasePlusSlugging());
        entity.setReachedOnError(dto.getErrors());
        entity.setWins(dto.getWins());
        entity.setLosses(dto.getLosses());
        entity.setSaves(dto.getSaves());
        entity.setInningsPitchedDecimal(dto.getInningsPitchedDecimal());
        entity.setTotalOutsPitched(dto.getTotalOutsPitched());
        entity.setInningsPitchedFull(dto.getInningsPitchedFull());
        entity.setInningsPitchedOuts(dto.getInningsPitchedOuts());
        entity.setEarnedRunAverage(dto.getEarnedRunAverage());
        entity.setPitchingHits(dto.getPitchingHits());
        entity.setPitchingRuns(dto.getPitchingRuns());
        entity.setPitchingEarnedRuns(dto.getPitchingEarnedRuns());
        entity.setPitchingWalks(dto.getPitchingWalks());
        entity.setPitchingStrikeouts(dto.getPitchingStrikeouts());
        entity.setPitchingHomeRuns(dto.getPitchingHomeRuns());
        entity.setPitchesThrown(dto.getPitchesThrown());
        entity.setPitchesThrownStrikes(dto.getPitchesThrownStrikes());
        entity.setWalksHitsPerInningsPitched(dto.getWalksHitsPerInningsPitched());
        entity.setPitchingBattingAverageAgainst(dto.getPitchingBattingAverageAgainst());
        entity.setGrandSlams(dto.getGrandSlams());
        entity.setFantasyPointsFanDuel(dto.getFantasyPointsFanDuel());
        entity.setFantasyPointsDraftKings(dto.getFantasyPointsDraftKings());
        entity.setFantasyPointsYahoo(dto.getFantasyPointsYahoo());
        entity.setPlateAppearances(dto.getPlateAppearances());
        entity.setTotalBases(dto.getTotalBases());
        entity.setFlyOuts(dto.getFlyOuts());
        entity.setGroundOuts(dto.getGroundOuts());
        entity.setLineOuts(dto.getLineOuts());
        entity.setPopOuts(dto.getPopOuts());
        entity.setIntentionalWalks(dto.getIntentionalWalks());
        entity.setReachedOnError(dto.getReachedOnError());
        entity.setBallsInPlay(dto.getBallsInPlay());
        entity.setBattingAverageOnBallsInPlay(dto.getBattingAverageOnBallsInPlay());
        entity.setWeightedOnBasePercentage(dto.getWeightedOnBasePercentage());
        entity.setPitchingSingles(dto.getPitchingSingles());
        entity.setPitchingDoubles(dto.getPitchingDoubles());
        entity.setPitchingTriples(dto.getPitchingTriples());
        entity.setPitchingGrandSlams(dto.getPitchingGrandSlams());
        entity.setPitchingHitByPitch(dto.getPitchingHitByPitch());
        entity.setPitchingSacrifices(dto.getPitchingSacrifices());
        entity.setPitchingSacrificeFlies(dto.getPitchingSacrificeFlies());
        entity.setPitchingGroundIntoDoublePlay(dto.getPitchingGroundIntoDoublePlay());
        entity.setPitchingCompleteGames(dto.getPitchingCompleteGames());
        entity.setPitchingShutOuts(dto.getPitchingShutOuts());
        entity.setPitchingNoHitters(dto.getPitchingNoHitters());
        entity.setPitchingPerfectGames(dto.getPitchingPerfectGames());
        entity.setPitchingPlateAppearances(dto.getPitchingPlateAppearances());
        entity.setPitchingTotalBases(dto.getPitchingTotalBases());
        entity.setPitchingFlyOuts(dto.getPitchingFlyOuts());
        entity.setPitchingGroundOuts(dto.getPitchingGroundOuts());
        entity.setPitchingLineOuts(dto.getPitchingLineOuts());
        entity.setPitchingPopOuts(dto.getPitchingPopOuts());
        entity.setPitchingIntentionalWalks(dto.getPitchingIntentionalWalks());
        entity.setPitchingReachedOnError(dto.getPitchingReachedOnError());
        entity.setPitchingCatchersInterference(dto.getPitchingCatchersInterference());
        entity.setPitchingBallsInPlay(dto.getPitchingBallsInPlay());
        entity.setPitchingOnBasePercentage(dto.getPitchingOnBasePercentage());
        entity.setPitchingSluggingPercentage(dto.getPitchingSluggingPercentage());
        entity.setPitchingOnBasePlusSlugging(dto.getPitchingOnBasePlusSlugging());
        entity.setPitchingStrikeoutsPerNineInnings(dto.getPitchingStrikeoutsPerNineInnings());
        entity.setPitchingWalksPerNineInnings(dto.getPitchingWalksPerNineInnings());
        entity.setPitchingBattingAverageOnBallsInPlay(dto.getPitchingBattingAverageOnBallsInPlay());
        entity.setPitchingWeightedOnBasePercentage(dto.getPitchingWeightedOnBasePercentage());
        entity.setDoublePlays(dto.getDoublePlays());
        entity.setPitchingDoublePlays(dto.getPitchingDoublePlays());
        entity.setBattingOrderConfirmed(dto.getBattingOrderConfirmed());
        entity.setIsolatedPower(dto.getIsolatedPower());
        entity.setFieldingIndependentPitching(dto.getFieldingIndependentPitching());
        entity.setPitchingQualityStarts(dto.getPitchingQualityStarts());
        entity.setPitchingInningStarted(dto.getPitchingInningStarted());
        entity.setLeftOnBase(dto.getLeftOnBase());
        entity.setPitchingHolds(dto.getPitchingHolds());
        entity.setPitchingBlownSaves(dto.getPitchingBlownSaves());
        entity.setSubstituteBattingOrder(dto.getSubstituteBattingOrder());
        entity.setSubstituteBattingOrderSequence(dto.getSubstituteBattingOrderSequence());
        entity.setFantasyPointsFantasyDraft(dto.getFantasyPointsFantasyDraft());
        entity.setFantasyPointsBatting(dto.getFantasyPointsBatting());
    }

    public IoPlayersStats toEntity(IoSportsDataPlayerStatsDTO dto) {
        return IoPlayersStats.builder()
                .statId(dto.getStatID())
                .teamId(dto.getTeamID())
                .playerId(dto.getPlayerID())
                .seasonType(dto.getSeasonType())
                .season(dto.getSeason())
                .name(dto.getName())
                .team(dto.getTeam())
                .position(dto.getPosition())
                .positionCategory(dto.getPositionCategory())
                .started(dto.getStarted())
                .battingOrder(dto.getBattingOrder())
                .globalTeamId(dto.getGlobalTeamID())
                .averageDraftPosition(dto.getAverageDraftPosition())
                .auctionValue(dto.getAuctionValue())
                .updated(dto.getUpdated())
                .games(dto.getGames())
                .fantasyPoints(dto.getFantasyPoints())
                .atBats(dto.getAtBats())
                .runs(dto.getRuns())
                .hits(dto.getHits())
                .singles(dto.getSingles())
                .doublesCount(dto.getDoubles())
                .triples(dto.getTriples())
                .homeRuns(dto.getHomeRuns())
                .runsBattedIn(dto.getRunsBattedIn())
                .battingAverage(dto.getBattingAverage())
                .outs(dto.getOuts())
                .strikeouts(dto.getStrikeouts())
                .walks(dto.getWalks())
                .hitByPitch(dto.getHitByPitch())
                .sacrifices(dto.getSacrifices())
                .sacrificeFlies(dto.getSacrificeFlies())
                .groundIntoDoublePlay(dto.getGroundIntoDoublePlay())
                .stolenBases(dto.getStolenBases())
                .caughtStealing(dto.getCaughtStealing())
                .pitchesSeen(dto.getPitchesSeen())
                .onBasePercentage(dto.getOnBasePercentage())
                .sluggingPercentage(dto.getSluggingPercentage())
                .onBasePlusSlugging(dto.getOnBasePlusSlugging())
                .errors(dto.getErrors())
                .wins(dto.getWins())
                .losses(dto.getLosses())
                .saves(dto.getSaves())
                .inningsPitchedDecimal(dto.getInningsPitchedDecimal())
                .totalOutsPitched(dto.getTotalOutsPitched())
                .inningsPitchedFull(dto.getInningsPitchedFull())
                .inningsPitchedOuts(dto.getInningsPitchedOuts())
                .earnedRunAverage(dto.getEarnedRunAverage())
                .pitchingHits(dto.getPitchingHits())
                .pitchingRuns(dto.getPitchingRuns())
                .pitchingEarnedRuns(dto.getPitchingEarnedRuns())
                .pitchingWalks(dto.getPitchingWalks())
                .pitchingStrikeouts(dto.getPitchingStrikeouts())
                .pitchingHomeRuns(dto.getPitchingHomeRuns())
                .pitchesThrown(dto.getPitchesThrown())
                .pitchesThrownStrikes(dto.getPitchesThrownStrikes())
                .walksHitsPerInningsPitched(dto.getWalksHitsPerInningsPitched())
                .pitchingBattingAverageAgainst(dto.getPitchingBattingAverageAgainst())
                .grandSlams(dto.getGrandSlams())
                .fantasyPointsFanDuel(dto.getFantasyPointsFanDuel())
                .fantasyPointsDraftKings(dto.getFantasyPointsDraftKings())
                .fantasyPointsYahoo(dto.getFantasyPointsYahoo())
                .plateAppearances(dto.getPlateAppearances())
                .totalBases(dto.getTotalBases())
                .flyOuts(dto.getFlyOuts())
                .groundOuts(dto.getGroundOuts())
                .lineOuts(dto.getLineOuts())
                .popOuts(dto.getPopOuts())
                .intentionalWalks(dto.getIntentionalWalks())
                .reachedOnError(dto.getReachedOnError())
                .ballsInPlay(dto.getBallsInPlay())
                .battingAverageOnBallsInPlay(dto.getBattingAverageOnBallsInPlay())
                .weightedOnBasePercentage(dto.getWeightedOnBasePercentage())
                .pitchingSingles(dto.getPitchingSingles())
                .pitchingDoubles(dto.getPitchingDoubles())
                .pitchingTriples(dto.getPitchingTriples())
                .pitchingGrandSlams(dto.getPitchingGrandSlams())
                .pitchingHitByPitch(dto.getPitchingHitByPitch())
                .pitchingSacrifices(dto.getPitchingSacrifices())
                .pitchingSacrificeFlies(dto.getPitchingSacrificeFlies())
                .pitchingGroundIntoDoublePlay(dto.getPitchingGroundIntoDoublePlay())
                .pitchingCompleteGames(dto.getPitchingCompleteGames())
                .pitchingShutOuts(dto.getPitchingShutOuts())
                .pitchingNoHitters(dto.getPitchingNoHitters())
                .pitchingPerfectGames(dto.getPitchingPerfectGames())
                .pitchingPlateAppearances(dto.getPitchingPlateAppearances())
                .pitchingTotalBases(dto.getPitchingTotalBases())
                .pitchingFlyOuts(dto.getPitchingFlyOuts())
                .pitchingGroundOuts(dto.getPitchingGroundOuts())
                .pitchingLineOuts(dto.getPitchingLineOuts())
                .pitchingPopOuts(dto.getPitchingPopOuts())
                .pitchingIntentionalWalks(dto.getPitchingIntentionalWalks())
                .pitchingReachedOnError(dto.getPitchingReachedOnError())
                .pitchingCatchersInterference(dto.getPitchingCatchersInterference())
                .pitchingBallsInPlay(dto.getPitchingBallsInPlay())
                .pitchingOnBasePercentage(dto.getPitchingOnBasePercentage())
                .pitchingSluggingPercentage(dto.getPitchingSluggingPercentage())
                .pitchingOnBasePlusSlugging(dto.getPitchingOnBasePlusSlugging())
                .pitchingStrikeoutsPerNineInnings(dto.getPitchingStrikeoutsPerNineInnings())
                .pitchingWalksPerNineInnings(dto.getPitchingWalksPerNineInnings())
                .pitchingBattingAverageOnBallsInPlay(dto.getPitchingBattingAverageOnBallsInPlay())
                .pitchingWeightedOnBasePercentage(dto.getPitchingWeightedOnBasePercentage())
                .doublePlays(dto.getDoublePlays())
                .pitchingDoublePlays(dto.getPitchingDoublePlays())
                .battingOrderConfirmed(dto.getBattingOrderConfirmed())
                .isolatedPower(dto.getIsolatedPower())
                .fieldingIndependentPitching(dto.getFieldingIndependentPitching())
                .pitchingQualityStarts(dto.getPitchingQualityStarts())
                .pitchingInningStarted(dto.getPitchingInningStarted())
                .leftOnBase(dto.getLeftOnBase())
                .pitchingHolds(dto.getPitchingHolds())
                .pitchingBlownSaves(dto.getPitchingBlownSaves())
                .substituteBattingOrder(dto.getSubstituteBattingOrder())
                .substituteBattingOrderSequence(dto.getSubstituteBattingOrderSequence())
                .fantasyPointsFantasyDraft(dto.getFantasyPointsFantasyDraft())
                .fantasyPointsBatting(dto.getFantasyPointsBatting())
                .build();
    }
}
