SET search_path TO sport;

CREATE TABLE IF NOT EXISTS settings
(
    name   VARCHAR(256) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT settings_PK PRIMARY KEY (name)
);

INSERT INTO settings VALUES('MOCK_ODDS');