SET
search_path TO sport;

CREATE TABLE io_players_stats
(
    id                                        BIGSERIAL PRIMARY KEY,
    stat_id                                   BIGINT ,
    team_id                                   BIGINT,
    player_id                                 BIGINT,
    season_type                               INTEGER,
    season                                    INTEGER,
    name                                      VARCHAR(50),
    team                                      VARCHAR(50),
    position                                  VARCHAR(50),
    position_category                         VARCHAR(50),
    started                                   INTEGER,
    batting_order                             TEXT,
    global_team_id                            BIGINT,
    average_draft_position                    TEXT,
    auction_value                             TEXT,
    updated                                   TIMESTAMP,
    games                                     INTEGER,
    fantasy_points                            DOUBLE PRECISION,
    at_bats                                   INTEGER,
    runs                                      INTEGER,
    hits                                      INTEGER,
    singles                                   INTEGER,
    doubles                                   INTEGER,
    triples                                   INTEGER,
    home_runs                                 INTEGER,
    runs_batted_in                            INTEGER,
    batting_average                           DOUBLE PRECISION,
    outs                                      INTEGER,
    strikeouts                                INTEGER,
    walks                                     INTEGER,
    hit_by_pitch                              INTEGER,
    sacrifices                                INTEGER,
    sacrifice_flies                           INTEGER,
    ground_into_double_play                   INTEGER,
    stolen_bases                              INTEGER,
    caught_stealing                           INTEGER,
    pitches_seen                              INTEGER,
    on_base_percentage                        DOUBLE PRECISION,
    slugging_percentage                       DOUBLE PRECISION,
    on_base_plus_slugging                     DOUBLE PRECISION,
    errors                                    INTEGER,
    wins                                      INTEGER,
    losses                                    INTEGER,
    saves                                     INTEGER,
    innings_pitched_decimal                   DOUBLE PRECISION,
    total_outs_pitched                        INTEGER,
    innings_pitched_full                      INTEGER,
    innings_pitched_outs                      INTEGER,
    earned_run_average                        DOUBLE PRECISION,
    pitching_hits                             INTEGER,
    pitching_runs                             INTEGER,
    pitching_earned_runs                      INTEGER,
    pitching_walks                            INTEGER,
    pitching_strikeouts                       INTEGER,
    pitching_home_runs                        INTEGER,
    pitches_thrown                            INTEGER,
    pitches_thrown_strikes                    INTEGER,
    walks_hits_per_innings_pitched            DOUBLE PRECISION,
    pitching_batting_average_against          DOUBLE PRECISION,
    grand_slams                               INTEGER,
    fantasy_points_fan_duel                   DOUBLE PRECISION,
    fantasy_points_draft_kings                DOUBLE PRECISION,
    fantasy_points_yahoo                      DOUBLE PRECISION,
    plate_appearances                         INTEGER,
    total_bases                               INTEGER,
    fly_outs                                  INTEGER,
    ground_outs                               INTEGER,
    line_outs                                 INTEGER,
    pop_outs                                  INTEGER,
    intentional_walks                         INTEGER,
    reached_on_error                          INTEGER,
    balls_in_play                             INTEGER,
    batting_average_on_balls_in_play          DOUBLE PRECISION,
    weighted_on_base_percentage               DOUBLE PRECISION,
    pitching_singles                          INTEGER,
    pitching_doubles                          INTEGER,
    pitching_triples                          INTEGER,
    pitching_grand_slams                      INTEGER,
    pitching_hit_by_pitch                     INTEGER,
    pitching_sacrifices                       INTEGER,
    pitching_sacrifice_flies                  INTEGER,
    pitching_ground_into_double_play          INTEGER,
    pitching_complete_games                   INTEGER,
    pitching_shut_outs                        INTEGER,
    pitching_no_hitters                       INTEGER,
    pitching_perfect_games                    INTEGER,
    pitching_plate_appearances                INTEGER,
    pitching_total_bases                      INTEGER,
    pitching_fly_outs                         INTEGER,
    pitching_ground_outs                      INTEGER,
    pitching_line_outs                        INTEGER,
    pitching_pop_outs                         INTEGER,
    pitching_intentional_walks                INTEGER,
    pitching_reached_on_error                 INTEGER,
    pitching_catchers_interference            INTEGER,
    pitching_balls_in_play                    INTEGER,
    pitching_on_base_percentage               DOUBLE PRECISION,
    pitching_slugging_percentage              DOUBLE PRECISION,
    pitching_on_base_plus_slugging            DOUBLE PRECISION,
    pitching_strikeouts_per_nine_innings      DOUBLE PRECISION,
    pitching_walks_per_nine_innings           DOUBLE PRECISION,
    pitching_batting_average_on_balls_in_play DOUBLE PRECISION,
    pitching_weighted_on_base_percentage      DOUBLE PRECISION,
    double_plays                              INTEGER,
    pitching_double_plays                     INTEGER,
    batting_order_confirmed                   BOOLEAN,
    isolated_power                            DOUBLE PRECISION,
    fielding_independent_pitching             DOUBLE PRECISION,
    pitching_quality_starts                   DOUBLE PRECISION,
    pitching_inning_started                   TEXT,
    left_on_base                              INTEGER,
    pitching_holds                            INTEGER,
    pitching_blown_saves                      INTEGER,
    substitute_batting_order                  TEXT,
    substitute_batting_order_sequence         TEXT,
    fantasy_points_fantasy_draft              DOUBLE PRECISION,
    fantasy_points_batting                    DOUBLE PRECISION,
    fantasy_points_pitching                   DOUBLE PRECISION
);
