CREATE SCHEMA IF NOT EXISTS sport;

CREATE TABLE sport.io_player_game_stats
(
    id                                        BIGSERIAL PRIMARY KEY,
    stat_id                                   BIGINT,
    team_id                                   BIGINT,
    player_id                                 BIGINT,
    season_type                               SMALLINT,
    season                                    SMALLINT,
    name                                      VARCHAR(100),
    team                                      CHAR(6),
    position                                  CHAR(6),
    position_category                         CHAR(6),
    started                                   SMALLINT,
    batting_order                             SMALLINT,

    fanduel_salary                            INTEGER,
    draftkings_salary                         INTEGER,
    fantasydata_salary                        INTEGER,
    yahoo_salary                              INTEGER,
    fanduel_position                          CHAR(6),
    draftkings_position                       CHAR(6),
    yahoo_position                            CHAR(6),
    fantasydraft_salary                       INTEGER,
    fantasydraft_position                     CHAR(6),

    injury_status                             VARCHAR(50),
    injury_body_part                          VARCHAR(50),
    injury_start_date                         DATE,
    injury_notes                              TEXT,

    game_id                                   BIGINT,
    global_game_id                            BIGINT,
    day                                       DATE,
    game_datetime                             TIMESTAMP,
    home_or_away                              CHAR(4),
    is_game_over                              BOOLEAN,
    updated                                   TIMESTAMP,


    opponent_id                               BIGINT,
    global_opponent_id                        BIGINT,
    opponent                                  CHAR(3),
    opponent_rank                             SMALLINT,
    opponent_position_rank                    SMALLINT,


    games                                     SMALLINT,
    fantasy_points                            NUMERIC(8, 2),


    at_bats                                   SMALLINT,
    runs                                      SMALLINT,
    hits                                      SMALLINT,
    singles                                   SMALLINT,
    doubles                                   SMALLINT,
    triples                                   SMALLINT,
    home_runs                                 SMALLINT,
    runs_batted_in                            SMALLINT,
    batting_average                           NUMERIC(6, 3),
    outs                                      SMALLINT,
    strikeouts                                SMALLINT,
    walks                                     SMALLINT,
    hit_by_pitch                              SMALLINT,
    sacrifices                                SMALLINT,
    sacrifice_flies                           SMALLINT,
    ground_into_double_play                   SMALLINT,
    stolen_bases                              SMALLINT,
    caught_stealing                           SMALLINT,
    pitches_seen                              SMALLINT,
    on_base_percentage                        NUMERIC(6, 3),
    slugging_percentage                       NUMERIC(6, 3),
    on_base_plus_slugging                     NUMERIC(6, 3),
    errors                                    SMALLINT,


    wins                                      SMALLINT,
    losses                                    SMALLINT,
    saves                                     SMALLINT,


    innings_pitched_decimal                   NUMERIC(6, 3),
    total_outs_pitched                        SMALLINT,
    innings_pitched_full                      SMALLINT,
    innings_pitched_outs                      SMALLINT,
    earned_run_average                        NUMERIC(6, 3),
    pitching_hits                             SMALLINT,
    pitching_runs                             SMALLINT,
    pitching_earned_runs                      SMALLINT,
    pitching_walks                            SMALLINT,
    pitching_strikeouts                       SMALLINT,
    pitching_home_runs                        SMALLINT,
    pitches_thrown                            SMALLINT,
    pitches_thrown_strikes                    SMALLINT,
    walks_hits_per_innings_pitched            NUMERIC(6, 3),
    pitching_batting_average_against          NUMERIC(6, 3),


    fantasy_points_fanduel                    NUMERIC(8, 2),
    fantasy_points_draftkings                 NUMERIC(8, 2),
    fantasy_points_yahoo                      NUMERIC(8, 2),
    fantasy_points_fantasydraft               NUMERIC(8, 2),
    fantasy_points_batting                    NUMERIC(8, 2),
    fantasy_points_pitching                   NUMERIC(8, 2),


    plate_appearances                         SMALLINT,
    total_bases                               SMALLINT,
    fly_outs                                  SMALLINT,
    ground_outs                               SMALLINT,
    line_outs                                 SMALLINT,
    pop_outs                                  SMALLINT,
    intentional_walks                         SMALLINT,
    reached_on_error                          SMALLINT,
    balls_in_play                             SMALLINT,
    batting_average_on_balls_in_play          NUMERIC(6, 3),
    weighted_on_base_percentage               NUMERIC(6, 3),


    pitching_singles                          SMALLINT,
    pitching_doubles                          SMALLINT,
    pitching_triples                          SMALLINT,
    pitching_grand_slams                      SMALLINT,
    pitching_hit_by_pitch                     SMALLINT,
    pitching_sacrifices                       SMALLINT,
    pitching_sacrifice_flies                  SMALLINT,
    pitching_ground_into_double_play          SMALLINT,
    pitching_complete_games                   SMALLINT,
    pitching_shut_outs                        SMALLINT,
    pitching_no_hitters                       SMALLINT,
    pitching_perfect_games                    SMALLINT,
    pitching_plate_appearances                SMALLINT,
    pitching_total_bases                      SMALLINT,
    pitching_fly_outs                         SMALLINT,
    pitching_ground_outs                      SMALLINT,
    pitching_line_outs                        SMALLINT,
    pitching_pop_outs                         SMALLINT,
    pitching_intentional_walks                SMALLINT,
    pitching_reached_on_error                 SMALLINT,
    pitching_catchers_interference            SMALLINT,
    pitching_balls_in_play                    SMALLINT,
    pitching_on_base_percentage               NUMERIC(6, 3),
    pitching_slugging_percentage              NUMERIC(6, 3),
    pitching_on_base_plus_slugging            NUMERIC(6, 3),
    pitching_strikeouts_per_nine_innings      NUMERIC(6, 2),
    pitching_walks_per_nine_innings           NUMERIC(6, 2),
    pitching_batting_average_on_balls_in_play NUMERIC(6, 3),
    pitching_weighted_on_base_percentage      NUMERIC(6, 3),


    double_plays                              SMALLINT,
    pitching_double_plays                     SMALLINT,
    batting_order_confirmed                   BOOLEAN,
    isolated_power                            NUMERIC(6, 3),
    fielding_independent_pitching             NUMERIC(6, 3),
    pitching_quality_starts                   SMALLINT,
    pitching_inning_started                   SMALLINT,
    left_on_base                              SMALLINT,
    pitching_holds                            SMALLINT,
    pitching_blown_saves                      SMALLINT,
    substitute_batting_order                  SMALLINT,
    substitute_batting_order_sequence         SMALLINT,
    global_team_id                            BIGINT,
    grand_slams                               SMALLINT
);


