SET search_path TO sport;

CREATE TABLE sport.io_player_stats_nfl (
    id BIGSERIAL PRIMARY KEY,
    player_id TEXT,
    season_type TEXT,
    season TEXT,
    team TEXT,
    number TEXT,
    name TEXT,
    position TEXT,
    position_category TEXT,
    activated TEXT,
    played TEXT,
    started TEXT,
    passing_attempts TEXT,
    passing_completions TEXT,
    passing_yards TEXT,
    passing_completion_percentage TEXT,
    passing_yards_per_attempt TEXT,
    passing_yards_per_completion TEXT,
    passing_touchdowns TEXT,
    passing_interceptions TEXT,
    passing_rating TEXT,
    passing_long TEXT,
    passing_sacks TEXT,
    passing_sack_yards TEXT,
    rushing_attempts TEXT,
    rushing_yards TEXT,
    rushing_yards_per_attempt TEXT,
    rushing_touchdowns TEXT,
    rushing_long TEXT,
    receiving_targets TEXT,
    receptions TEXT,
    receiving_yards TEXT,
    receiving_yards_per_reception TEXT,
    receiving_touchdowns TEXT,
    receiving_long TEXT,
    fumbles TEXT,
    fumbles_lost TEXT,
    punt_returns TEXT,
    punt_return_yards TEXT,
    punt_return_yards_per_attempt TEXT,
    punt_return_touchdowns TEXT,
    punt_return_long TEXT,
    kick_returns TEXT,
    kick_return_yards TEXT,
    kick_return_yards_per_attempt TEXT,
    kick_return_touchdowns TEXT,
    kick_return_long TEXT,
    solo_tackles TEXT,
    assisted_tackles TEXT,
    tackles_for_loss TEXT,
    sacks TEXT,
    sack_yards TEXT,
    quarterback_hits TEXT,
    passes_defended TEXT,
    fumbles_forced TEXT,
    fumbles_recovered TEXT,
    fumble_return_yards TEXT,
    fumble_return_touchdowns TEXT,
    interceptions TEXT,
    interception_return_yards TEXT,
    interception_return_touchdowns TEXT,
    blocked_kicks TEXT,
    special_teams_solo_tackles TEXT,
    special_teams_assisted_tackles TEXT,
    misc_solo_tackles TEXT,
    misc_assisted_tackles TEXT,
    punts TEXT,
    punt_yards TEXT,
    punt_average TEXT,
    field_goals_attempted TEXT,
    field_goals_made TEXT,
    field_goals_longest_made TEXT,
    extra_points_made TEXT,
    two_point_conversion_passes TEXT,
    two_point_conversion_runs TEXT,
    two_point_conversion_receptions TEXT,
    fantasy_points TEXT,
    fantasy_points_ppr TEXT,
    reception_percentage TEXT,
    receiving_yards_per_target TEXT,
    tackles TEXT,
    offensive_touchdowns TEXT,
    defensive_touchdowns TEXT,
    special_teams_touchdowns TEXT,
    touchdowns TEXT,
    fantasy_position TEXT,
    field_goal_percentage TEXT,
    player_season_id TEXT,
    fumbles_own_recoveries TEXT,
    fumbles_out_of_bounds TEXT,
    kick_return_fair_catches TEXT,
    punt_return_fair_catches TEXT,
    punt_touchbacks TEXT,
    punt_inside20 TEXT,
    punt_net_average TEXT,
    extra_points_attempted TEXT,
    blocked_kick_return_touchdowns TEXT,
    field_goal_return_touchdowns TEXT,
    safeties TEXT,
    field_goals_had_blocked TEXT,
    punts_had_blocked TEXT,
    extra_points_had_blocked TEXT,
    punt_long TEXT,
    blocked_kick_return_yards TEXT,
    field_goal_return_yards TEXT,
    punt_net_yards TEXT,
    special_teams_fumbles_forced TEXT,
    special_teams_fumbles_recovered TEXT,
    misc_fumbles_forced TEXT,
    misc_fumbles_recovered TEXT,
    short_name TEXT,
    safeties_allowed TEXT,
    temperature TEXT,
    humidity TEXT,
    wind_speed TEXT,
    offensive_snaps_played TEXT,
    defensive_snaps_played TEXT,
    special_teams_snaps_played TEXT,
    offensive_team_snaps TEXT,
    defensive_team_snaps TEXT,
    special_teams_team_snaps TEXT,
    auction_value TEXT,
    auction_value_ppr TEXT,
    two_point_conversion_returns TEXT,
    fantasy_points_fanduel TEXT,
    field_goals_made0to19 TEXT,
    field_goals_made20to29 TEXT,
    field_goals_made30to39 TEXT,
    field_goals_made40to49 TEXT,
    field_goals_made50plus TEXT,
    fantasy_points_draftkings TEXT,
    fantasy_points_yahoo TEXT,
    average_draft_position TEXT,
    average_draft_position_ppr TEXT,
    team_id TEXT,
    global_team_id TEXT,
    fantasy_points_fantasydraft TEXT,
    average_draft_position_rookie TEXT,
    average_draft_position_dynasty TEXT,
    average_draft_position2qb TEXT,
    offensive_fumble_recovery_touchdowns TEXT,
    game_id TEXT
);

CREATE INDEX idx_io_player_game_stats_nfl_player_id ON sport.io_player_game_stats_nfl(player_id);
CREATE INDEX idx_io_player_game_stats_nfl_team ON sport.io_player_game_stats_nfl(team);
CREATE INDEX idx_io_player_game_stats_nfl_season ON sport.io_player_game_stats_nfl(season);

CREATE TABLE sport.io_player_scoring_detail_nfl (
    id BIGSERIAL PRIMARY KEY,
    game_key TEXT,
    season_type TEXT,
    player_id TEXT,
    team TEXT,
    season TEXT,
    week TEXT,
    scoring_type TEXT,
    length TEXT,
    scoring_detail_id TEXT,
    player_game_id TEXT,
    scoring_play_id TEXT,
    player_game_stats_id BIGINT REFERENCES sport.io_player_game_stats_nfl(id)
);

CREATE INDEX idx_io_player_scoring_detail_nfl_player_id ON sport.io_player_scoring_detail_nfl(player_id);
CREATE INDEX idx_io_player_scoring_detail_nfl_player_game_stats_id ON sport.io_player_scoring_detail_nfl(player_game_stats_id);
CREATE INDEX idx_io_player_scoring_detail_nfl_game_key ON sport.io_player_scoring_detail_nfl(game_key);
CREATE INDEX idx_io_player_scoring_detail_nfl_season ON sport.io_player_scoring_detail_nfl(season);
CREATE INDEX idx_io_player_scoring_detail_nfl_week ON sport.io_player_scoring_detail_nfl(week);



