SET search_path TO sport;

CREATE TABLE IF NOT EXISTS io_player_nfl (
    id BIGSERIAL PRIMARY KEY,

    player_id BIGINT,
    team TEXT,
    number INTEGER,
    first_name TEXT,
    last_name TEXT,
    position TEXT,
    status TEXT,
    height TEXT,
    weight INTEGER,
    birth_date DATE,
    college TEXT,
    experience INTEGER,
    fantasy_position TEXT,
    active BOOLEAN,
    position_category TEXT,
    name TEXT,
    age INTEGER,
    experience_string TEXT,
    birth_date_string TEXT,
    photo_url TEXT,
    bye_week INTEGER,
    upcoming_game_opponent TEXT,
    upcoming_game_week INTEGER,
    short_name TEXT,
    average_draft_position DOUBLE PRECISION,
    depth_position_category TEXT,
    depth_position TEXT,
    depth_order INTEGER,
    depth_display_order INTEGER,
    current_team TEXT,
    college_draft_team TEXT,
    college_draft_year INTEGER,
    college_draft_round INTEGER,
    college_draft_pick INTEGER,
    is_undrafted_free_agent BOOLEAN,
    height_feet INTEGER,
    height_inches INTEGER,
    upcoming_opponent_rank INTEGER,
    upcoming_opponent_position_rank INTEGER,
    current_status TEXT,
    upcoming_salary INTEGER,

    fantasy_alarm_player_id TEXT,
    sport_radar_player_id TEXT,
    rotoworld_player_id TEXT,
    roto_wire_player_id TEXT,
    stats_player_id TEXT,
    sports_direct_player_id TEXT,
    xml_team_player_id TEXT,
    fan_duel_player_id TEXT,
    draft_kings_player_id TEXT,
    yahoo_player_id TEXT,

    injury_status TEXT,
    injury_body_part TEXT,
    injury_start_date TEXT,
    injury_notes TEXT,

    fan_duel_name TEXT,
    draft_kings_name TEXT,
    yahoo_name TEXT,

    fantasy_position_depth_order INTEGER,
    injury_practice TEXT,
    injury_practice_description TEXT,
    declared_inactive BOOLEAN,
    upcoming_fan_duel_salary INTEGER,
    upcoming_draft_kings_salary INTEGER,
    upcoming_yahoo_salary INTEGER,

    team_id INTEGER,
    global_team_id BIGINT,
    fantasy_draft_player_id TEXT,
    fantasy_draft_name TEXT,

    usa_today_player_id TEXT,
    usa_today_headshot_url TEXT,
    usa_today_headshot_no_background_url TEXT,
    usa_today_headshot_updated TIMESTAMP,
    usa_today_headshot_no_background_updated TIMESTAMP
);
