name: Deploy to ECS

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:

env:
  ECR_REPOSITORY: flexbets-dev
  ECS_CLUSTER: dev-cluster
  ECS_SERVICE: dev-service
  ECS_TASK: mock-api

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=${GITHUB_SHA::7}
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: ./.github/workflows/oidc
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        env:
          IMAGE_TAG: ${{ env.COMMIT_SHORT_SHA }}
          IMAGE_TAG_RESULT: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG .
          docker image list
          docker push ${{ env.IMAGE_TAG_RESULT }}
  update-task-definition:
    needs: [build-and-push]
    name: Update ECS task definition
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: ./.github/workflows/oidc
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: Update ECS task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK }}-task \
            --query taskDefinition --output json > task-raw.json
          jq 'del(.compatibilities, .taskDefinitionArn, .requiresAttributes, .revision, .status, .registeredAt, .registeredBy)' task-raw.json > task-clear.json
          jq '.taskDefinition.containerDefinitions[0].image = "${{ env.IMAGE_TAG_RESULT }}"' task-clear.json > task-definition.json

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          wait-for-service-stability: true
