name: Deploy to ECS

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:

env:
  ecr_repository: flexbets-dev

jobs:
  build-app:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Cache Dependency-Check NVD database
        uses: actions/cache@v4
        with:
          path: dependency-check/data
          key: dependency-check-nvd-${{ runner.os }}-${{ github.run_number }}
          restore-keys: |
            dependency-check-nvd-${{ runner.os }}-

      - name: Build .jar
        run: |
          chmod +x gradlew
          ./gradlew dependencies --no-daemon
          ./gradlew build -x test --no-daemon

      - name: Dependency check
        run: |
          VERSION=$(curl -s https://dependency-check.github.io/DependencyCheck/current.txt) && \
          curl -Ls "https://github.com/dependency-check/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip && \
          unzip dependency-check.zip && \
          dependency-check/bin/dependency-check.sh \
            --out . \
            --scan ~/.gradle/caches \
            --format JSON \
            --prettyPrint

      - name: Upload dependency check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: ./*.json

      - name: Upload .jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: build/libs/*.jar

  docker-image:
    needs: [build-app]
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      image_tag_result: ${{ steps.build-and-push.outputs.image_tag_result }}
    steps:
      - uses: actions/checkout@v4

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=${GITHUB_SHA::7}
          echo "commit_short_sha=$calculatedSha" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: ./.github/workflows/oidc
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - run: ls -lah *.jar

      - name: Download .jar artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - run: ls -lah *.jar

      - name: Build and Push Docker image
        id: build-and-push
        env:
          image_tag: ${{ env.commit_short_sha }}
          image_tag_result: ${{ steps.login-ecr.outputs.registry }}/$ecr_repository:$image_tag
        run: |
          docker build . -t ${{ steps.login-ecr.outputs.registry }}/$ecr_repository:$image_tag
          docker image list
          docker push ${{ env.image_tag_result }}
          echo "image_tag_result=${{ env.image_tag_result }}" >> $GITHUB_OUTPUT

      - name: Delete .jar artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: app

  # update-ecs-dev:
  #   env:
  #     ecs_cluster: dev-cluster
  #     ecs_service: dev-service
  #     ecs_task: dev-api
  #   needs: [docker-image]
  #   name: Update ECS task (dev)
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Configure AWS credentials
  #       uses: ./.github/workflows/oidc
  #       with:
  #         role-to-assume: ${{ secrets.IAM_ROLE }}

  #     - name: Update ECS task definition
  #       run: |
  #         aws ecs describe-task-definition --task-definition ${{ env.ecs_task }}-task \
  #           --query taskDefinition --output json > task-raw.json
  #         jq 'del(.compatibilities,
  #           .taskDefinitionArn,
  #           .requiresAttributes,
  #           .revision, .status,
  #           .registeredAt,
  #           .registeredBy)' \
  #           task-raw.json > task-clear.json
  #         jq '
  #         .containerDefinitions[0].image =
  #         "${{ needs.docker-image.outputs.image_tag_result }}"
  #         ' task-clear.json > task-definition.json

  #     - name: Deploy to ECS
  #       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  #       with:
  #         task-definition: task-definition.json
  #         cluster: ${{ env.ecs_cluster }}
  #         service: ${{ env.ecs_service }}
  #         wait-for-service-stability: true

  # update-ecs-stage:
  #   env:
  #     ecs_cluster: stage-cluster
  #     ecs_service: stage-service
  #     ecs_task: stage-api
  #   needs: [docker-image]
  #   name: Update ECS task (stage)
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Configure AWS credentials
  #       uses: ./.github/workflows/oidc
  #       with:
  #         role-to-assume: ${{ secrets.IAM_ROLE }}

  #     - name: Update ECS task definition
  #       run: |
  #         aws ecs describe-task-definition --task-definition ${{ env.ecs_task }}-task \
  #           --query taskDefinition --output json > task-raw.json
  #         jq 'del(.compatibilities,
  #           .taskDefinitionArn,
  #           .requiresAttributes,
  #           .revision, .status,
  #           .registeredAt,
  #           .registeredBy)' \
  #           task-raw.json > task-clear.json
  #         jq '
  #         .containerDefinitions[0].image =
  #         "${{ needs.docker-image.outputs.image_tag_result }}"
  #         ' task-clear.json > task-definition.json

  #     - name: Deploy to ECS
  #       uses: aws-actions/amazon-ecs-deploy-task-definition@v1
  #       with:
  #         task-definition: task-definition.json
  #         cluster: ${{ env.ecs_cluster }}
  #         service: ${{ env.ecs_service }}
  #         wait-for-service-stability: true
