name: Deploy to ECS

on:
  push:
    branches: [main, feat/ci-docker]
  workflow_dispatch:

jobs:
  build-app:
    name: Build application
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ecr_repository: flexbets
    outputs:
      image_tag_result: ${{ steps.build-and-push.outputs.image_tag_result }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}-

      - name: Build .jar
        run: |
          chmod +x gradlew
          ./gradlew dependencies --no-daemon
          ./gradlew build -x test --no-daemon

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=${GITHUB_SHA::7}
          echo "commit_short_sha=$calculatedSha" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: ./.github/actions/oidc
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        id: build-and-push
        env:
          image_tag: ${{ env.commit_short_sha }}
          image_tag_result: ${{ steps.login-ecr.outputs.registry }}/$ecr_repository:$image_tag
        run: |
          docker build . -t ${{ env.image_tag_result }}
          docker push ${{ env.image_tag_result }}
          echo "image_tag_result=${{ env.image_tag_result }}" >> $GITHUB_OUTPUT

  update-ecs:
      needs: [build-app]
      name: Update ECS Task (${{ matrix.env }})
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      strategy:
        matrix:
          env: [dev,stage,prd]
      env:
        ecs_cluster: ${{ matrix.env }}
        ecs_service: sports
      steps:
        - run: echo ${{ matrix.env }}
        - uses: actions/checkout@v4
          id: checkout

        - name: Configure AWS credentials
          id: aws-credentials
          uses: ./.github/actions/oidc
          with:
            role-to-assume: ${{ secrets.IAM_ROLE }}

        - name: Update ECS task definition
          id: task-def-update
          timeout-minutes: 3
          run: |
            aws ecs describe-task-definition --task-definition ${{ matrix.env }}-${{ env.ecs_service }} \
              --query taskDefinition --output json > task-raw.json
            jq 'del(.compatibilities,
              .taskDefinitionArn,
              .requiresAttributes,
              .revision, .status,
              .registeredAt,
              .registeredBy)' \
              task-raw.json > task-clear.json
            jq --arg image "${{ needs.build-app.outputs.image_tag_result }}" --arg name "flexbets-sports" '
              .containerDefinitions |= map(
              if .name == $name then
                .image = $image
              else
                .
              end
              )' task-clear.json > task-definition.json

        - name: Deploy to ECS
          uses: aws-actions/amazon-ecs-deploy-task-definition@v1
          with:
            task-definition: task-definition.json
            cluster: ${{ env.ecs_cluster }}
            service: ${{ env.ecs_service }}
            wait-for-service-stability: true
